# TEST --- 


#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [2]:
Z = np.zeros((10,10))
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 3. How to find the memory size of any array (★☆☆)

In [3]:
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)

In [4]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 5. Reverse a vector (first element becomes last) (★☆☆)

In [5]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 6. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [6]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 7. Create a 3x3 identity matrix (★☆☆)

In [7]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 8. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [8]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
1) 0 * np.nan
2) np.nan == np.nan
3) np.inf > np.nan
4) np.nan - np.nan
5) np.nan in set([np.nan])
6) 0.3 == 3 * 0.1
```

In [9]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 9. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [10]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 10. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [11]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 11. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [12]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 12. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [13]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 13. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [14]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 14. Create a random vector of size 10 and sort it (★★☆)

In [15]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 15. Generate a generic 2D Gaussian-like array (★★☆)

In [16]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 16. Find the nearest value from a given value in an array (★★☆)

In [21]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4557016877993496


#### 17. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [22]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.43490817 0.53871865 0.54374184 0.43938384 0.35823706 0.38813204
 0.50832838 0.454516   0.52029627 0.44895924]
0    0.434908
1    0.538719
2    0.543742
3    0.439384
4    0.358237
5    0.388132
6    0.508328
7    0.454516
8    0.520296
9    0.448959
dtype: float64


#### 18. How to get the diagonal of a dot product? (★★★)

In [23]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([1.25498854, 1.30854716, 1.37250478, 1.25988182, 0.98238999])

#### 19. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [24]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.81786717, 0.05874151, 0.59747844, 0.17546777, 0.57993449,
        0.47423574, 0.35990173, 0.43678533, 0.64476651, 0.65150953],
       [0.91555219, 0.06575752, 0.66884051, 0.19642542, 0.64920114,
        0.53087786, 0.40288794, 0.48895442, 0.72177661, 0.72932501],
       [0.16145286, 0.011596  , 0.11794654, 0.0346386 , 0.11448324,
        0.09361755, 0.07104719, 0.08622457, 0.12728155, 0.12861267],
       [0.38818333, 0.02788041, 0.28358049, 0.08328206, 0.27525362,
        0.22508595, 0.17081973, 0.20731091, 0.30602477, 0.3092252 ],
       [0.14357638, 0.01031206, 0.10488719, 0.03080332, 0.10180735,
        0.08325197, 0.06318066, 0.07667756, 0.1131886 , 0.11437233],
       [0.39056282, 0.02805132, 0.28531879, 0.08379256, 0.27694088,
        0.22646569, 0.17186683, 0.20858169, 0.30790064, 0.31112069],
       [0.63041785, 0.04527838, 0.46054065, 0.13525181, 0.44701765,
        0.36554429, 0.27741482, 0.33667725, 0.49699063, 0.5021882 ],
       [0.72817943, 0.05229989, 0.5319586

# 20. Calculate Gradient Descent on 1 example (★★★)

```python
Calculate Z with following the formular. Z = W.T * X + B 
W = A vector with values ranging from 0 to 63.
X = A vector with values 1 with 8 x 8 array.
B = A vector with values 1 with 8 x 8 array.

hint: dot() 
hint: .T mean transpose
hint: dimention of Z is 8 x 8
hint: print(Z)


Calculate A with function sigmoid(Z).
sigmoid() = 1 /(1 + e^(-Z))


```


In [59]:
import math 

X = np.arange(8 * 8).reshape(8, 8)
W = np.ones((8 , 8))
B = np.ones((8 , 8))

Z = np.dot(W.T, X) + B

def sigmoid(Z): 
    return 1/(1 + np.exp(-Z))

A = sigmoid(Z)
print(A)

    



[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
